language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
env:
  - PHPUNIT_VERSION="5"
  - PHPUNIT_VERSION="6"
  - PHPUNIT_VERSION="7"
  - PHPUNIT_VERSION="8"
matrix:
  # Check the last supported PHPUnit for legacy PHP versions, and check all
  # combinations of current PHP and PHPUnit versions.
  include:
    - php: '5.6'
      env: PHPUNIT_VERSION="5"
    - php: '7.0'
      env: PHPUNIT_VERSION="6"
    - php: '7.1'
      env: PHPUNIT_VERSION="7"
    - php: '7.2'
      env: PHPUNIT_VERSION="7"
    - php: '7.3'
      env: PHPUNIT_VERSION="7"
    - php: '7.2'
      env: PHPUNIT_VERSION="8"
    - php: '7.3'
      env: PHPUNIT_VERSION="8"
install:
  - composer require phpunit/phpunit:^${PHPUNIT_VERSION} --update-with-dependencies
  - composer install --no-interaction
